# -*- coding: utf-8 -*-
"""アフター用

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6-V8VDLuOWmmiskMwEZHNXE4nSHyptL
"""

import streamlit as st
import pygetwindow as gw
import pyautogui
import time
import win32print

# ウィンドウを取得
if st.button('実行')
  window = gw.getWindowsWithTitle('FMServlet.fmcsm - imageWARE From Manager CSM Client')[0]
  window.activate()

  # Ctrl+Pを押す
  pyautogui.hotkey('ctrl', 'p')
  time.sleep(2)  # 印刷ダイアログが表示されるまで待機

  # プリンター名を設定
  printer_name = "Microsoft Print to PDF"
  win32print.SetDefaultPrinter(printer_name)

  # ファイル名を入力して保存
  pyautogui.typewrite('241101637.pdf')
  pyautogui.press('enter')

